### PR TITLE
RFC: saving of "viewed" state

### PR DESCRIPTION
**Pull request by jacekkopecky**
Firstly, thank you for making this extension, it's really useful since I can't find anything around VS Code that can show me whole diffs rather than file-by-file.

This pull request is really a request for comments – I don't know if you like the direction or the code style... Anyway:

With this PR, the extension can save (in the diff file itself) what files you've _viewed_. On reloading a diff file, it will hide those files automatically.

Small improvements also included:

* show a count of viewed and all files in a footer,
* make the file header sticky so that the "viewed" checkbox is always in view and you don't have to scroll up after reviewing a file,
* automatically reload the diff file is it's changed externally.

I'll be happy to answer any question or explain anything that's not clear. Let me know what you think.

### CODE REVIEW

**Comment by caponetto** [comment]
Hi @jacekkopecky! Thanks for your contribution and interest!
I'll take a look at the code as soon as possible.
In the meantime, could you please run `yarn format` and commit the changes?

**Comment by jacekkopecky** [comment]
Sorry, of course, done. I have a new coding environment and it obviously hasn't picked up the prettier config. My bad.

**Comment by jacekkopecky** [comment]
@caponetto I realize that it's rather large-ish and combines multiple changes; I now also have a new addition in my fork at https://github.com/jacekkopecky/vscode-diff-viewer/tree/hyperlinks where you can click on a line number or on the file name and VSCode opens that file (on that line).

I've been thinking about it and maybe I could split my contributions like this:

1. refactor to use CustomTextEditor and automatically reload the diff file is it's changed externally,
2. make the file header sticky so it stays at the top of the window as you scroll through a longer file,
3. click on line number of filename to go to the file,
4. show a count of viewed files and all files in a footer,
5. (and the one that may need the most discussion last) save "viewed" state in the diff file.

Would you like that? Should I do just the first one for now so you can review it and suggest which one next?

**Comment by caponetto** [comment]
Hey @jacekkopecky,
Sounds good to me! I think splitting the code like you've said helps us moving forward faster. :)

**Comment by jacekkopecky** [comment]
Closing, will split into more manageable pieces.

**Pull request closed without merging**
